# Generated by Django 2.2 on 2019-10-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191002_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='currentIssue',
            new_name='current_issue',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='firstName',
            new_name='length_of_issue',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastName',
            new_name='recent_changes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lengthOfIssue',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='recentChanges',
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
