# Generated by Django 2.2.6 on 2019-10-30 20:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191030_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='allergies',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('N', 'None'), ('L', 'Latex'), ('P', 'Penicillin'), ('A', 'Aspirin'), ('I', 'Iodine'), ('S', 'Shellfish'), ('O', 'Other')], default=None, max_length=13),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='patient',
            name='fam_hist',
        ),
        migrations.AddField(
            model_name='patient',
            name='fam_hist',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hbp', 'High blood pressure'), ('hd', 'Heart disease/heart attack'), ('diab', 'Diabetes'), ('arth', 'Arthritis')], default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='patient',
            name='med_hist',
        ),
        migrations.AddField(
            model_name='patient',
            name='med_hist',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bleed', 'Bleeding Problems'), ('anemia', 'Anemia'), ('hbp', 'High blood pressure'), ('hd', 'Heart disease/heart attack'), ('af', 'atrial Fibrillation'), ('pace', 'Pacemaker'), ('lung', 'Lung Disease'), ('copd', 'COPD/emphysema'), ('kd', 'Kidney disease'), ('liv', 'Liver disease'), ('hep', 'Hepatitis'), ('col', 'Colitis'), ('div', 'Diverticulitis'), ('ulc', 'Ulcers/GERD'), ('thy', 'Thyroid problems'), ('lup', 'Lupus'), ('arth', 'Arthritis'), ('gout', 'Gout'), ('park', "Parkinson's"), ('stroke', 'Stroke/TIA'), ('seiz', 'Seizures'), ('DVT', 'Phlebitis/DVT (blood clot)'), ('ven', 'Venereal disease'), ('canc', 'Cancer'), ('asth', 'Asthma'), ('diab', 'Diabetes'), ('hiv', 'HIV or AIDS'), ('hc', 'High Cholesterol')], default=None, max_length=125),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AllergyChoice',
        ),
        migrations.DeleteModel(
            name='FamHistChoice',
        ),
        migrations.DeleteModel(
            name='MedHistChoice',
        ),
    ]
