# Generated by Django 2.2.6 on 2019-10-30 21:09

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191030_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='med_hist',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bleed', 'Bleeding Problems'), ('anemia', 'Anemia'), ('hbp', 'High blood pressure'), ('hd', 'Heart disease/heart attack'), ('af', 'Atrial Fibrillation'), ('pace', 'Pacemaker'), ('lung', 'Lung Disease'), ('copd', 'COPD/emphysema'), ('kd', 'Kidney disease'), ('liv', 'Liver disease'), ('hep', 'Hepatitis'), ('col', 'Colitis'), ('div', 'Diverticulitis'), ('ulc', 'Ulcers/GERD'), ('thy', 'Thyroid problems'), ('lup', 'Lupus'), ('arth', 'Arthritis'), ('gout', 'Gout'), ('park', "Parkinson's"), ('stroke', 'Stroke/TIA'), ('seiz', 'Seizures'), ('DVT', 'Phlebitis/DVT (blood clot)'), ('ven', 'Venereal disease'), ('canc', 'Cancer'), ('asth', 'Asthma'), ('diab', 'Diabetes'), ('hiv', 'HIV or AIDS'), ('hc', 'High Cholesterol')], max_length=125),
        ),
    ]
