# Generated by Django 2.2.6 on 2019-11-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20191113_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='start_details',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='start',
            field=models.DateField(),
        ),
    ]
