# Generated by Django 2.2.6 on 2019-11-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191113_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='fam_other_hist',
            new_name='other_fam_hist',
        ),
    ]
