# Generated by Django 2.2.6 on 2019-11-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191113_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='issue_description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrar', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(max_length=30),
        ),
    ]
